server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://43.143.153.47:3306/jc-club?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: sinker
    password: yyZENrTZB+txscucviw9rAKiAcQkIqY0GAMBjjr/LC4HlFCmJjSYICCUnIPjIIqNAQ2xyBVzxq7Lb79HU5sPng==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
  jackson:
    default-property-inclusion: non_null
logging:
  config: classpath:log4j-spring.xml

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANvGhox8HX6Fx740AK6BjNEPApNyFxwpjAuGmhXgNJ725Y+SwJSd8s+1P2YuknrO3IRwrKSUEt4ODFQdPsy0JP0CAwEAAQ==

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl